server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/smsdb
    username: smsuser
    password: smspass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
